source 'https://rubygems.org'

ruby "2.0.0"

gem 'rails', '3.2.16'
gem 'pg'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :development do
  gem 'debugger'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :test do
  gem 'guard-rspec'
end

gem 'bcrypt-ruby', '~> 3.0.0', require: 'bcrypt'
gem 'faker'
gem "figaro", "~> 0.7"
gem "paperclip", "~> 3.0"
gem "aws-sdk", "~> 1.34"
gem 'addressable', "~> 2.3", require: 'addressable/uri'
gem 'rest_client', "~> 1.7"
gem "omniauth-google-oauth2", "~> 0.2"

gem "kaminari", "~> 0.15"

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

